# Generated by Django 4.2.1 on 2023-06-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
